import { JetBrains_Mono } from "next/font/google";
import Header from "@/components/ui/Header";
import "./globals.css";
import PageTransition from "@/components/ui/PageTransition";
import Stairtransition from "@/components/Stairtransition";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"]

});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <Header />
        <Stairtransition />
        <PageTransition>
          {children}
        </PageTransition>


      </body>
    </html>
  );
}
